language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_31e08961829b_key -iv $encrypted_31e08961829b_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 47.104.66.25\n\tPort 22\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo "I am in 47.104.66.25"
install:
- npm install
script:
- npm run test
after_success:
- npm prune --production
- tar -jcf travis-server.tar.bz2 *
- scp travis-server.tar.bz2 liuxuan@47.104.66.25:/home/liuxuan/
addons:
    ssh_known_hosts: 47.104.66.25
