language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_aa7f44cf7988_key -iv $encrypted_aa7f44cf7988_iv -in travis_rsa.enc -out ~/.ssh/travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
- echo -e "Host 47.104.66.25\n\tPort 22\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo "I am in 47.104.66.25"
install:
- npm install
script:
- npm run test
after_success:
- npm prune --production
- tar -cf travis-server.tar *
- scp -i ~/.ssh/travis_rsa travis-server.tar liuxuan@47.104.66.25:/home/liuxuan/travis
addons:
  ssh_known_hosts: 47.104.66.25
